### ISSUE TITLE
Show 64/32 bits apps

### ISSUE THREAD

**Issue by stissot** [serhii-londar/open-source-mac-os-apps#152]
Apple will remove 32 bits applications support in the next release of macOS.

The list should have icons to show which apps are 64 bits compatible, or better - since the majority will eventually be 64 bits - an icon for the apps are 32 bits only.

**Comment by Coeur** [comment]
If they are open source, doesn't it mean that all of them can be re-built from source for compatibility with 64 bits?

**Comment by serhii-londar** [comment]
I agree with @Coeur. Not all apps from this list are in the app store. And you can rebuild them with 64 bits support.
