### ISSUE TITLE
Carol - a menu bar lyrics app

### ISSUE THREAD

**Issue by AnaghSharma** [serhii-londar/open-source-mac-os-apps#197]
Hi, 

I have recently developed [this app - Carol](https://github.com/AnaghSharma/Carol) having minimal and beautiful design which shows lyrics on demand. Would love to have it added to the list.

Thanks.

**Comment by serhii-londar** [comment]
Hi @AnaghSharma! Nice app! You can just create Pull Request.

**Comment by AnaghSharma** [comment]
@serhii-londar So I went through the CONTRIBUTING.md and checked the format for adding an app. The app is developed in C# which is not listed in the languages. Should I add it?

**Comment by serhii-londar** [comment]
@AnaghSharma Yes. Please add icon image to icon folder and update readme to support it.

**Comment by AnaghSharma** [comment]
Added in c7ac462ce6a951bbc6921e14a0d604f46f62d251
