### ISSUE TITLE
Different ordering approach?

### ISSUE THREAD

**Issue by justinclift** [serhii-londar/open-source-mac-os-apps#216]
Would it be ok to have a most useful ordering approach (eg alphabetical) instead of the current random (chronological) one?  The sections themselves are ordered alphabetically, which seems to indicate that's already recognised as optimal for lookup purposes.

Chronological doesn't seem useful for any purpose other than "whoever adds their app to a new section first gets highest listing".  Probably not a great goal. :wink:

**Comment by justinclift** [comment]
What's a good way to get this done?  I can send in PR's for a few sections at a time, or (if given write access) I can just make changes directly, or maybe some other approach would be better?

**Comment by serhii-londar** [comment]
@justinclift  I think we can do it by section. So it will be good to create PR for every section. What do you think?

**Comment by justinclift** [comment]
Hmmm, that seems workable.  I'll get a few started now, and we'll see how quickly we can whip through the lot. :smile:

We'll need the PR template updated to say "alphabetical" after that's done too.

**Comment by justinclift** [comment]
At the moment there's a top level "Other" category sort of hanging around in the middle of things.

Guessing that category itself should be moved into alphabetical order too?

**Comment by justinclift** [comment]
Hmmm, this is taking longer than expected doing it one section at a time.  I'll try bundling a few together to speed it up. :smile:

**Comment by justinclift** [comment]
K, they're all done, with the exception of the Downloader -> Other category, which I'm not sure what to do with (yet).  Let me know (as per above) and I'll make a PR to get that one done too. :smile:

**Comment by serhii-londar** [comment]
@justinclift That's a great job from you! Thank you for your hard work!

**Comment by serhii-londar** [comment]
I think we can close it as you finished with all sections. Agree?

**Comment by justinclift** [comment]
The Downloader -> Other section still needs dealing with.

The entries there don't seem "Downloader" related.  I'm thinking we should just move them to a new "Other" section.  And maybe have that at the end instead of alphabetical?  Not 100% sure though. :smile:

**Comment by justinclift** [comment]
If #243 is merged, I **think** this could be closed. :smile:

**Comment by serhii-londar** [comment]
@justinclift Merged. Thank you! 👍 Great job!

**Comment by justinclift** [comment]
No worries.  It looks heaps better now. :smile:
