### ISSUE TITLE
Keka is not actually open source?

### ISSUE THREAD

**Issue by ngocphamm** [serhii-londar/open-source-mac-os-apps#222]
The github link with the item is not where the source code is. According to the main README file, and [this issue](https://github.com/aonez/Keka/issues/13), the app is not open-source, yet.

**Comment by serhii-londar** [comment]
@justinclift Thanks fixing it!

**Comment by justinclift** [comment]
No worries at all.  Thanks @ngocphamm for pointing out the problem. :smile:

**Comment by justinclift** [comment]
Ahhh, should I close my PR for it?
