### ISSUE TITLE
Add Larpon/DeadAscend

### ISSUE THREAD

**Issue by Larpon** [serhii-londar/open-source-mac-os-apps#255]
For the games section
https://github.com/Larpon/DeadAscend

**Comment by serhii-londar** [comment]
@Larpon it is only for iOS and Android.

**Comment by Larpon** [comment]
No. It's written with Qt (cross-platform application framework) and builds fine on MacOS? I know because I'm the developer and happen to have a Mac I've built it on. It's easy to build for MacOS. Download Qt Creator and do a few `git clone` and that's it. Oh well

**Comment by serhii-londar** [comment]
@Larpon I know what is Qt) But on download page there are links to iOS and Android, so I'm not sure that it is adapted to desktop.

**Comment by Larpon** [comment]
That's because the Android and iOS binaries are more complex to build due to the setup of  QtFirebase. On desktops it's easy to build yourself. But you're right there's no pre-built binaries for desktop (only in some Linux package managers) - I didn't know that existing binaries were a criteria - my bad! I might provide them when I get some more time on my hands!

**Comment by serhii-londar** [comment]
Please provide it and let me know. After that, I think it can be added to this list. Also you can create PR and add it :)

**Comment by Larpon** [comment]
Noted :smile:
