### ISSUE TITLE
Add ColorSet

### ISSUE THREAD

**Issue by serhii-londar** [serhii-londar/open-source-mac-os-apps#295]
https://github.com/DigiDNA/ColorSet

**Comment by naclcaleb** [comment]
I'd like to do this one. Is there anything I should know before starting?

**Comment by serhii-londar** [comment]
@serhii-londar Please create PR according to [Guide](https://github.com/serhii-londar/open-source-mac-os-apps/blob/master/CONTRIBUTING.md).
