### ISSUE TITLE
protracker and fasttracker2

### ISSUE THREAD

**Issue by alexmyczko** [serhii-londar/open-source-mac-os-apps#336]
Almost right..

[Protracker](https://16-bits.org/pt.php) - Music tracker clone of ProTracker v2.3D for modern computers <img src='https://screenshots.debian.net/screenshots/000/015/839/large.png' widht="400"/>

[Fasttracker II](https://16-bits.org/ft2.php) - Fasttracker II clone music tracker.

**Comment by kenken1mura** [comment]
stop
