### ISSUE TITLE
Loading Apps pictures

### ISSUE THREAD

**Issue by hussamzain** [serhii-londar/open-source-mac-os-apps#370]
It takes (52 Sec) to load the page until all apps pictures downloaded! can you delete them from the main page?

![image](https://user-images.githubusercontent.com/42704207/54762792-ff896600-4bb1-11e9-81c6-47c149779a4e.png)

**Comment by serhii-londar** [comment]
@hussamzain Good idea. Thank you for reporting 👍

**Comment by hussamzain** [comment]
What a nice update 😃(it takes only 2.3 Sec)

![image](https://user-images.githubusercontent.com/42704207/54850154-9255fd80-4ca3-11e9-9675-edaf4692e466.png)

Thanks 🙏🙏🏿
