### ISSUE TITLE
This repo is cool. Can I translate it to Chinese ?

### ISSUE THREAD

**Issue by nusr** [serhii-londar/open-source-mac-os-apps#388]

**Comment by serhii-londar** [comment]
@nusr Good idea. But currently, I have no answer how to do this in a proper way.

**Comment by nusr** [comment]
README.md is generated by json, so we can create two json files.

applications.json  <--> applications-zh.json
categories.json <--> categories-zh.json
Even create directory ,that's better.

**Comment by serhii-londar** [comment]
Yes, but in the future, we will need to add applications and categories in two files. That's not comfortable.

**Comment by serhii-londar** [comment]
A better way is to add a new field for applications: something like "description-zh".

**Comment by nusr** [comment]
Yes.It's better.
