### ISSUE TITLE
Dozer is not open source

### ISSUE THREAD

**Issue by ZetiX** [serhii-londar/open-source-mac-os-apps#407]
Dozer's github page only contains a demo folder containing a gif file. The page also states that it's not open source.

**Comment by serhii-londar** [comment]
@ZetiX Thank you for highlighting this.

**Comment by peppy** [comment]
Full source is back on this one (https://github.com/Mortennn/Dozer)

**Comment by serhii-londar** [comment]
@peppy Thanks! Will add it back 👍
