### ISSUE TITLE
Quickwords has a duplicate language icon

### ISSUE THREAD

**Issue by HankiDesign** [serhii-londar/open-source-mac-os-apps#448]
As seen in the image below, JavaScript icon shows up twice for Quickwords. This issue shows up on multiple browsers (tested on Firefox/macOS and Chrome/Android):

![Screenshot 2019-10-09 at 09 41 42](https://user-images.githubusercontent.com/1816448/66461326-15407900-ea79-11e9-92b1-85d0ccd02089.png)

I checked the applications.json file and the definition seems correct to me:

```
"title": "Quickwords",
"icon_url": "",
"screenshots": [
    "https://i.imgur.com/asCk1Ds.png"
 ],
 "official_site": "",
 "languages": [
     "javascript",
     "css"
 ]
```

**Comment by MatsLanGoH** [comment]
Taking this up. There's also a duplicate icon for Oni.
Both apps contain an additional `![javascript]` inside the short description, causing the duplicate icon to show up.
