### ISSUE TITLE
How to run readmeGenerator?

### ISSUE THREAD

**Issue by skywinder** [serhii-londar/open-source-mac-os-apps#494]
Hi. I found a brilliant idea to made generator instead of manuall building Readme. 👍 

I want to improe it a little bit, but can't run.

I open `.github/ReadmeGenerator.xcodeproj`

Then run program and got this warning:

![Screenshot 2019-12-28 at 23 10 27](https://user-images.githubusercontent.com/3356474/71549018-9ef04a80-29c7-11ea-877e-3e3e29dc6642.png)
I don't know, where is your name comes from, look like so absolute path settled, but 

`grep -iR "Users/serhii-londar/" ./**` doesn't shoe any matches.

If I continue to run the project, got the error output:

```swift
Start
Error Domain=NSCocoaErrorDomain Code=260 "The file “applications.json” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/pk/Library/Developer/Xcode/DerivedData/ReadmeGenerator-fmeoviztnomraycobfgvbwocervo/Build/Products/Debug/applications.json, NSUnderlyingError=0x103851400 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Program ended with exit code: 0
```

Please, help to run `main.swift` and I would be glad to improve this script! 👍

**Comment by serhii-londar** [comment]
@skywinder Hi!

You should set up a custom working directory path for the scheme. Tap on scheme -> Edit scheme: 

<img width="222" alt="Screenshot 2019-12-28 at 23 06 46" src="https://user-images.githubusercontent.com/15808174/71549484-f6da8180-29c6-11ea-8f20-11fb29a26a3a.png">

Then you should check "Use custom working directory" and set folder with applications.json file:

<img width="897" alt="Screenshot 2019-12-28 at 23 05 30" src="https://user-images.githubusercontent.com/15808174/71549486-f9d57200-29c6-11ea-86ae-960df2575e3b.png">


Or you can run it without Xcode. In terminal run `swift main.swift` and it will run the script. You will need to run it from the root folder so you can use `swift ./.github/main.swift`.

**Comment by skywinder** [comment]
Lovely! Thanks for your quick support!

btw, 
it's first time , that I see such feature for readme generation, but thought, that it could be a standart to avoid mess. Did you create this or borrow from some other implementation?


p.s. 
I found, that use wrong grep params, that's why I didn't found this string:

`grep -irn "/Users/serhii-londar/Documents/GitHub/open-source-mac-os-apps" ./`

this works :)

**Comment by serhii-londar** [comment]
I saw similar implementations in other repositories. But I implemented it on swift by my own.
