### ISSUE TITLE
Any apps to prevent mac from sleep? 🤔

### ISSUE THREAD

**Issue by skywinder** [serhii-londar/open-source-mac-os-apps#503]
Like caffeine of amphetanine, but open source. Is anybody knows alternative?

**Comment by skywinder** [comment]
Looks like https://github.com/newmarcel/KeepingYouAwake is a good option for this category.

**Comment by serhii-londar** [comment]
@skywinder Feel free to add a new category.

**Comment by skywinder** [comment]
whoops. found it in System category alreade.
sorry, just searched with wrong words (keep, lid, power)
