### ISSUE TITLE
App Suggestion to List: the0neyouseek/MonitorControl

### ISSUE THREAD

**Issue by walksonair** [serhii-londar/open-source-mac-os-apps#555]
I'd like to recommend https://github.com/the0neyouseek/MonitorControl to be added to your awesome list. I was in need of controlling the audio and brightness for my USB-C monitor from my mac without having to go through the monitor's HW controls all the time. https://github.com/the0neyouseek/MonitorControl did the trick!

**Comment by itsjwala** [comment]
duplicated by #616
