### ISSUE TITLE
is it an applicaiton if you need an IDE to run it?

### ISSUE THREAD

**Issue by CouldBeThis** [serhii-londar/open-source-mac-os-apps#626]
re https://github.com/DeromirNeves/VerticalBar

instructions for use start with "Open this project with XCode 9+."

my personal feeling is that something that needs an IDE to run it is not an application but a source code. Assuming it is not something that is obviously of interest only to developers, in which case I suppose more assumptions can be made. 

I think this contributes to the idea that using free software requires advanced technical skills. 

Reasonable minds may differ on this question; just my input.

**Comment by serhii-londar** [comment]
@CouldBeThis Unfortunately not all projects have uploaded releases. And the idea of this list is to share apps with open source code. I think you can open an issue in this repository and ask for publishing release.
