### ISSUE TITLE
Suggested app: Monitor Bar

### ISSUE THREAD

**Issue by tidiemme** [serhii-londar/open-source-mac-os-apps#637]
I'm suggesting my app here because I used this list to find similar apps as inspiration and was really helpful so thought It was nice to post it here.

I was looking for a nice monitor bar similar to the one I used to have in Linux, but could not find one so I built one.

![](https://github.com/tidiemme/monitorbar/raw/main/mb.png)

[https://github.com/tidiemme/monitorbar](https://github.com/tidiemme/monitorbar)

This is my first app for Mac and my first app in swift, hope you like it.
Any comment/suggestion appreciated.

**Comment by parikhparth23** [comment]
Created a PR - https://github.com/parikhparth23/open-source-mac-os-apps/commit/fdabac4adaac45dddcd0e140a918e039030d3fdb

**Comment by parikhparth23** [comment]
Created a PR - https://github.com/serhii-londar/open-source-mac-os-apps/pull/790
