### ISSUE TITLE
App suggestion

### ISSUE THREAD

**Issue by itsjwala** [serhii-londar/open-source-mac-os-apps#644]
Hello, I don't know if this is the right place to ask questions.

so I have a monitor hooked up to my mac and I need to swap windows between mac and the monitor.

Is there any app for the same, I couldn't find any API calls to do so or I would have written a script for the same.

Any suggestion is appreciated, Thanks!

**Comment by rpietzsch** [comment]
You should check out the tools in the http://localhost/#window-management category. This should get you covered.

**Comment by itsjwala** [comment]
I already checked them, none of them suit my use case. 

Basically, I want to swap all the windows(full screen or not) from mac to monitor and vice versa

**Comment by relikd** [comment]
does not belong here. Please close the issue @itsjwala
