### ISSUE TITLE
New Logo design

### ISSUE THREAD

**Issue by serhii-londar** [serhii-londar/open-source-mac-os-apps#77]
Draw new project logo for repository header.

**Comment by serhii-londar** [comment]
@jraulhernandezi You can put here your ideas for new logo design.

**Comment by jraulhernandezi** [comment]
Ok, working on it!

**Comment by serhii-londar** [comment]
@jraulhernandezi Thank you so much!

**Comment by jraulhernandezi** [comment]
![image](https://user-images.githubusercontent.com/35578070/38825415-78496498-417a-11e8-8a35-e3e97abdb593.png)

I used the open source logo and inside it I put a list reference, I´m working on other colors and the typography, let me know what do you think.

**Comment by jraulhernandezi** [comment]
![image](https://user-images.githubusercontent.com/35578070/38825996-798e4dee-417c-11e8-838c-0bf952251b51.png)
This one with the mac OS colors of the  "X" version.

**Comment by jraulhernandezi** [comment]
![image](https://user-images.githubusercontent.com/35578070/38827788-0267b9c0-4182-11e8-9ee1-81ea9d6b085b.png)
A simpler version, using mac colors, I´m trying to keep it simple. Working on some other ideas.

**Comment by jraulhernandezi** [comment]
Maybe something like this for the banner.
![image](https://user-images.githubusercontent.com/35578070/38828263-8687d40a-4183-11e8-97b6-e09ba5c70637.png)

**Comment by serhii-londar** [comment]
The last two images look nice!

**Comment by jraulhernandezi** [comment]
![image](https://user-images.githubusercontent.com/35578070/38830086-2b13fbac-4189-11e8-958e-c5d492014d4c.png)

**Comment by jraulhernandezi** [comment]
Do you have any suggestion? Or should I send more ideas?

**Comment by serhii-londar** [comment]
If you can provide some more examples it will be great. If not this logos is ok for me.

**Comment by jraulhernandezi** [comment]
![macos](https://user-images.githubusercontent.com/35578070/38843604-d2934674-41bd-11e8-86b4-9df69a1ac903.jpg)
![512 logo negro](https://user-images.githubusercontent.com/35578070/38843613-dd75cae4-41bd-11e8-9948-2d7ccf23fc67.png)
![512 logo color](https://user-images.githubusercontent.com/35578070/38843666-24f6bd88-41be-11e8-9a7a-5f132bc619a1.png)



I was trying some new ideas but, this one was the best for sure, I propose the first one as the banner image. Also I upload the color version of the logo and B/W. What do you think? Is it worth the merge?

**Comment by serhii-londar** [comment]
@jraulhernandezi Thanks for your hard work! I think we can use the last one! I like it!

**Comment by jraulhernandezi** [comment]
That´s great, I will send you the original vector files in a few moments.

**Comment by serhii-londar** [comment]
@jraulhernandezi I've updated a logo! 🎉 Thank you for contributing our project! Appreciate your work!

**Comment by jraulhernandezi** [comment]
Awesome! I´m glad you like it. 

[Original files](https://drive.google.com/open?id=1MqYpyKNRYGCJIbnew93WU19_EM1itna7)
